---
name: build
on:
  schedule:
    - cron: "00 02 1 * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository_id }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}    
    
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4

      - name: Generate image tags
        id: generate-image-tags
        shell: bash
        run: |
          TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
          DATE="$(echo ${TIMESTAMP} | cut -d '-' -f 1)"
          echo "DATE=$DATE" >> $GITHUB_ENV
          BUILD_TAGS=( "latest" "${TIMESTAMP}" "${DATE}" )
          echo "alias_tags=${BUILD_TAGS[*]}" >> $GITHUB_OUTPUT

      - name: Define Image Metadata
        id: define-image-metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/cubt85iz/toolbx/main/README.md
            org.opencontainers.image.description=A container image for ${{ env.IMAGE_NAME }}
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.version=${{ env.DATE }}

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          context: ./
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ steps.generate-image-tags.outputs.alias_tags }}
          labels: ${{ steps.define-image-metadata.outputs.labels }}
          oci: false

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Sign container
      - uses: sigstore/cosign-installer@v3.2.0
        if: github.event_name != 'pull_request'

      - name: Sign container image
        if: github.event_name != 'pull_request'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build_image.outputs.image }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Echo outputs
        #if: github.event_name != 'pull_request'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
